// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo3f7eAD1FV0uLSJsK4AQUdTqoE8d8atg',
    appId: '1:828020795062:web:bb6df1d9e724100133a817',
    messagingSenderId: '828020795062',
    projectId: 'ta-chat-nhate',
    authDomain: 'ta-chat-nhate.firebaseapp.com',
    storageBucket: 'ta-chat-nhate.firebasestorage.app',
    measurementId: 'G-L1KVM5YF9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz7G6J21ycbH95mvTyKPqk_SUZIo8XpJg',
    appId: '1:828020795062:android:00d6a93437fd462633a817',
    messagingSenderId: '828020795062',
    projectId: 'ta-chat-nhate',
    storageBucket: 'ta-chat-nhate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDom3D3pm6KOKUZZL8HsFIPwQnZZyH-_Nw',
    appId: '1:828020795062:ios:f22eb918a55aa91633a817',
    messagingSenderId: '828020795062',
    projectId: 'ta-chat-nhate',
    storageBucket: 'ta-chat-nhate.firebasestorage.app',
    iosBundleId: 'com.example.pyinMalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDom3D3pm6KOKUZZL8HsFIPwQnZZyH-_Nw',
    appId: '1:828020795062:ios:f22eb918a55aa91633a817',
    messagingSenderId: '828020795062',
    projectId: 'ta-chat-nhate',
    storageBucket: 'ta-chat-nhate.firebasestorage.app',
    iosBundleId: 'com.example.pyinMalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo3f7eAD1FV0uLSJsK4AQUdTqoE8d8atg',
    appId: '1:828020795062:web:5abbb539bf1e2ec533a817',
    messagingSenderId: '828020795062',
    projectId: 'ta-chat-nhate',
    authDomain: 'ta-chat-nhate.firebaseapp.com',
    storageBucket: 'ta-chat-nhate.firebasestorage.app',
    measurementId: 'G-Q5QNBLHKD7',
  );
}
